### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by JingxuanKang** [dvlab-research/LISA#38]
Hi:
I tried to use a single 3090(24G) to debug. It is the default setting, but it shows that CUDA is out of memory.
How to run this in a single GPU?

**Comment by X-Lai** [comment]
May I know if you use the latest version repo?

**Comment by X-Lai** [comment]
Actually, we recommend using 8 * 3090 GPUs to train a 7B model, since we use deepspeed ZeRO stage 2 to split the optimizer and gradients into multiple GPUs, so this can save much GPU memory. If you use only a single GPU, then all the optimizer and gradients are saved into a single GPU, and this could lead to OOM.

**Comment by JingxuanKang** [comment]
Yeah, I use the latest version. And I think that's the reason a single GPU doesn't work.

**Comment by X-Lai** [comment]
> @JingxuanKang Hello, did you merge this model "./output/LLaVA-7B-v1 "? Could you please send me a copy? Thank you.

You can follow the instructions in the README.md file.
